
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '607BEB0A3C2B644207B106E565247FD0'
    
_lr_action_items = {'SELECT':([0,],[3,]),'TEXT':([7,],[8,]),';':([8,9,],[-5,10,]),'$end':([1,2,4,10,],[-1,0,-2,-3,]),'*':([3,],[5,]),'FROM':([5,6,],[-4,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement_list':([0,],[1,]),'input':([0,],[2,]),'table_reference':([7,],[9,]),'statement':([0,],[4,]),'select_list':([3,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> statement_list','input',1,'p_input','FormatSql.py',17),
  ('statement_list -> statement','statement_list',1,'p_statement_list','FormatSql.py',21),
  ('statement -> SELECT select_list FROM table_reference ;','statement',5,'p_statement_select','FormatSql.py',25),
  ('select_list -> *','select_list',1,'p_select_list','FormatSql.py',29),
  ('table_reference -> TEXT','table_reference',1,'p_table_reference','FormatSql.py',33),
]
